GET http://localhost:5000/

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "test2",
  "email": "test2@example.com",
  "password": "test2111"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test6@example.com",
  "password": "test111"
}

### Create a flashcard
POST http://localhost:5000/api/flashcards
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjA3MmM3NTQ1MjBiMGZkYzY4YzRiNyIsImlhdCI6MTc1NjM5NDE4NCwiZXhwIjoxNzU2Mzk3Nzg0fQ.VpmHgCrMlkV5kjgYSc9cD5wbwL7sjWaQmWqTAD5YMJg

{
  "question": "name 3 states of matter?",
  "answer": "Solid, Liquid and Gas"
}

### Get all flashcards
GET http://localhost:5000/api/flashcards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjE4NjQxMDllZjY1YWNiYjU5ZmU1NCIsImlhdCI6MTc1NjkyMjAyMCwiZXhwIjoxNzU2OTI1NjIwfQ.M8Zw2vx6BR50Jghf5PZJqZ0lEUeqgARxutFVFdI8Mbw

###

POST http://localhost:5000/api/ai-flashcards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjA3MmM3NTQ1MjBiMGZkYzY4YzRiNyIsImlhdCI6MTc1NjY1NzMzNCwiZXhwIjoxNzU2NjYwOTM0fQ.JKhjgZbI-e1fD7asui_yC3gNruhDfDLl7aL_kMGALZw
Content-Type: application/json

{
  "text": "Artificial Intelligence is a branch of computer science that aims to create machines that can perform tasks that typically require human intelligence."
}
